# Generated by Django 5.0.4 on 2024-04-24 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactentry',
            options={'verbose_name_plural': 'Contact Entries'},
        ),
    ]
