# Generated by Django 5.0.4 on 2024-04-24 18:58

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeWebsite', '0002_alter_contactentry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactentry',
            name='date',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
